feature_params:
  maxCorners: 100
  qualityLevel: 0.3
  minDistance: 7
  blockSize: 7
lk_params:
  winSize: !!python/tuple [15, 15]
  maxLevel: 2
  criteria: !!python/tuple [3, 10, 0.03]
diff_limit: 1.0
brightness_limit: 20.0